[package]
name = "chrysalis"
description = "Surface programming language compiling to the prism process-bigraph runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prism-schema = { workspace = true }
prism-bigraph = { workspace = true }
prism-std = { workspace = true }
prism-trace = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
indexmap = { workspace = true }
ordered-float = { workspace = true }
compact_str = { workspace = true }
rand = { workspace = true }
rustyline = "14"

[dev-dependencies]
prism-viz = { workspace = true }
