//! Load all spatio-flux fixture JSON documents from the Python test suite report.
//!
//! These are the actual composite documents generated by the Python spatio-flux
//! test suite at https://vivarium-collective.github.io/spatio-flux/report/
//!
//! Tests marked READY use only process types we have implemented.
//! Tests marked BLOCKED skip gracefully when a required process type is missing.

use std::sync::Arc;
use prism_bigraph::VivariumDocument;
use spatio_flux::from_config::build_registry;
use spatio_flux::vivarium_loader::instantiate_vivarium;

const FIXTURES: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures");

/// Load a fixture JSON, parse it, instantiate if possible, run, and report.
fn run_fixture(name: &str, duration: f64) {
    let path = format!("{FIXTURES}/{name}.json");
    let json = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{name}: cannot read {path}: {e}"));

    let vdoc = VivariumDocument::from_json(&json)
        .unwrap_or_else(|e| panic!("{name}: parse error: {e}"));

    let n_procs = vdoc.processes.len();
    let proc_types: Vec<String> = vdoc
        .processes
        .values()
        .map(|p| p.class_name.clone())
        .collect();

    println!("{name}: {n_procs} processes — {proc_types:?}");

    let registry = Arc::new(build_registry());

    match instantiate_vivarium(&vdoc, Arc::clone(&registry)) {
        Ok((mut engine, _topology)) => {
            engine.run(duration);

            // Verify simulation advanced
            assert!(
                engine.time() > 0.0,
                "{name}: simulation should advance time"
            );

            // Report final state
            let state = engine.state();
            if let Some(map) = state.as_map() {
                let keys: Vec<&prism_schema::Key> = map.keys().collect();
                println!("  OK — t={:.1}, state keys: {keys:?}", engine.time());
            }
        }
        Err(e) => {
            println!("  SKIPPED — {e}");
        }
    }
}

// ────────────────────────────────────────────────────
// READY: these use only implemented process types
// ────────────────────────────────────────────────────

#[test]
fn fixture_monod_kinetics() {
    run_fixture("monod_kinetics", 60.0);
}

#[test]
fn fixture_diffusion_process() {
    run_fixture("diffusion_process", 60.0);
}

#[test]
fn fixture_brownian_particles() {
    run_fixture("brownian_particles", 20.0);
}

#[test]
fn fixture_br_particles_kinetics() {
    run_fixture("br_particles_kinetics", 20.0);
}

// ────────────────────────────────────────────────────
// BLOCKED on DynamicFBA
// ────────────────────────────────────────────────────

#[test]
fn fixture_ecoli_core_dfba() {
    run_fixture("ecoli_core_dfba", 10.0);
}

#[test]
fn fixture_ecoli_dfba() {
    run_fixture("ecoli_dfba", 10.0);
}

#[test]
fn fixture_yeast_dfba() {
    run_fixture("yeast_dfba", 10.0);
}

#[test]
fn fixture_community_dfba() {
    run_fixture("community_dfba", 10.0);
}

#[test]
fn fixture_dfba_kinetics_community() {
    run_fixture("dfba_kinetics_community", 10.0);
}

#[test]
fn fixture_spatial_many_dfba() {
    run_fixture("spatial_many_dfba", 10.0);
}

#[test]
fn fixture_br_particles_dfba() {
    run_fixture("br_particles_dfba", 10.0);
}

#[test]
fn fixture_comets_diffusion() {
    run_fixture("comets_diffusion", 10.0);
}

#[test]
fn fixture_comets_br_particles_dfba() {
    run_fixture("comets_br_particles_dfba", 10.0);
}

// ────────────────────────────────────────────────────
// BLOCKED on SpatialDFBA
// ────────────────────────────────────────────────────

#[test]
fn fixture_spatial_dfba_process() {
    run_fixture("spatial_dfba_process", 10.0);
}

#[test]
fn fixture_comets_br_particles_kinetics() {
    run_fixture("comets_br_particles_kinetics", 10.0);
}

// ────────────────────────────────────────────────────
// BLOCKED on PymunkParticleMovement
// ────────────────────────────────────────────────────

#[test]
fn fixture_newtonian_particles() {
    run_fixture("newtonian_particles", 10.0);
}

#[test]
fn fixture_comets_nt_particles_dfba() {
    run_fixture("comets_nt_particles_dfba", 10.0);
}

// ────────────────────────────────────────────────────
// BLOCKED on multiple missing types
// ────────────────────────────────────────────────────

#[test]
fn fixture_spatioflux_reference_demo() {
    run_fixture("spatioflux_reference_demo", 10.0);
}

// ────────────────────────────────────────────────────
// Cross-boundary correctness: a composite's inner process must
// actually change the OUTER fields (not just "run"). This is the
// exchange / inner-particle path the units context-factor routing
// would ride.
// ────────────────────────────────────────────────────

fn sum_leaves(v: &prism_schema::Value) -> f64 {
    match v {
        prism_schema::Value::Map(m) => m.values().map(sum_leaves).sum(),
        prism_schema::Value::List(l) => l.iter().map(sum_leaves).sum(),
        prism_schema::Value::Struct { values, .. } => values.iter().map(sum_leaves).sum(),
        other => other.as_f64().unwrap_or(0.0),
    }
}

#[test]
fn spatial_dfba_changes_outer_fields() {
    let path = format!("{FIXTURES}/spatial_many_dfba.json");
    let json = std::fs::read_to_string(&path).unwrap();
    let vdoc = VivariumDocument::from_json(&json).unwrap();
    let registry = Arc::new(build_registry());
    let (mut engine, _topo) =
        instantiate_vivarium(&vdoc, Arc::clone(&registry)).expect("should instantiate");

    let fields_key = [prism_schema::Key::from("fields")];
    let before = engine.state().get_path(&fields_key).map(sum_leaves).unwrap_or(0.0);
    engine.run(10.0);
    let after = engine.state().get_path(&fields_key).map(sum_leaves).unwrap_or(0.0);

    // The `spatial_dFBA` composite reads/writes the outer fields across
    // the sub-engine boundary. If cross-boundary exchange works the
    // field total moves; if it's silently broken (the flagged bug) it
    // stays put.
    assert!(
        (before - after).abs() > 1e-9,
        "spatial_dFBA composite did not change outer fields (before={before}, after={after}) \
         — cross-boundary exchange is silently inert"
    );
}

#[test]
fn reference_demo_depletes_glucose() {
    // The exact scenario the 49-day-old note flagged: the `spatial_kinetics`
    // composite holds dFBA processes nested INSIDE particles
    // (`particles.p_xxx.ecoli_1 dFBA`) whose wires are particle-relative.
    // The note said glucose stuck at 5.0 (no depletion). Diffusion
    // conserves the field total, so any DECREASE in total glucose is
    // genuine consumption routed across the particle/composite boundary.
    let path = format!("{FIXTURES}/spatioflux_reference_demo.json");
    let json = std::fs::read_to_string(&path).unwrap();
    let vdoc = VivariumDocument::from_json(&json).unwrap();
    let registry = Arc::new(build_registry());
    let (mut engine, _topo) =
        instantiate_vivarium(&vdoc, Arc::clone(&registry)).expect("should instantiate");

    let glucose = [prism_schema::Key::from("fields"), prism_schema::Key::from("glucose")];
    let before = engine.state().get_path(&glucose).map(sum_leaves).unwrap_or(0.0);
    engine.run(20.0);
    let after = engine.state().get_path(&glucose).map(sum_leaves).unwrap_or(0.0);

    println!("reference_demo glucose total: {before} -> {after}");
    assert!(
        after < before - 1e-9,
        "glucose should deplete via inner-particle dFBA across the composite boundary, \
         but total went {before} -> {after}"
    );
}
