//! Statistical operationalizations for coda data.
//!
//! `LagAutocorrelation` computes lag-1 Pearson autocorrelation of ICIs within
//! each coda, pooled across the corpus, with a Z-score and two-tailed p-value
//! from a within-coda shuffle null. The standard test against Sharma 2024's
//! rubato claim: if ICI sequences carry serial structure within codas, the
//! observed mean lag-1 corr should be significantly distant from the null
//! distribution generated by shuffling each coda's ICIs independently.

use std::any::Any;

use indexmap::IndexMap;
use prism_bigraph::{ProcessNode, ProcessRegistry, Schema, Step, Update, Value};
use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};

#[derive(Debug)]
pub struct LagAutocorrelation {
    n_permutations: usize,
    seed: u64,
}

impl LagAutocorrelation {
    pub fn from_config(config: &Value) -> Self {
        let n_permutations = config
            .get_field("n_permutations")
            .and_then(|v| v.as_f64())
            .map(|f| f as usize)
            .unwrap_or(10_000);
        let seed = config
            .get_field("seed")
            .and_then(|v| v.as_f64())
            .map(|f| f as u64)
            .unwrap_or(42);
        Self {
            n_permutations,
            seed,
        }
    }
}

fn lag1_corr(xs: &[f64]) -> Option<f64> {
    let n = xs.len();
    if n < 3 {
        return None;
    }
    pearson(&xs[..n - 1], &xs[1..])
}

fn pearson(a: &[f64], b: &[f64]) -> Option<f64> {
    let n = a.len();
    if n != b.len() || n < 2 {
        return None;
    }
    let nf = n as f64;
    let mean_a = a.iter().sum::<f64>() / nf;
    let mean_b = b.iter().sum::<f64>() / nf;
    let (mut cov, mut var_a, mut var_b) = (0.0_f64, 0.0_f64, 0.0_f64);
    for i in 0..n {
        let da = a[i] - mean_a;
        let db = b[i] - mean_b;
        cov += da * db;
        var_a += da * da;
        var_b += db * db;
    }
    let denom = (var_a * var_b).sqrt();
    if denom > 0.0 {
        Some(cov / denom)
    } else {
        None
    }
}

fn shuffle_in_place<R: Rng>(rng: &mut R, xs: &mut [f64]) {
    let n = xs.len();
    for i in (1..n).rev() {
        let j = rng.gen_range(0..=i);
        xs.swap(i, j);
    }
}

impl Step for LagAutocorrelation {
    fn inputs(&self) -> IndexMap<String, Schema> {
        IndexMap::from([("codas".to_string(), Schema::Any)])
    }

    fn outputs(&self) -> IndexMap<String, Schema> {
        IndexMap::from([("measurement".to_string(), Schema::Any)])
    }

    fn update(&self, state: &Value) -> Update {
        let codas: &[Value] = state
            .get_field("codas")
            .and_then(|v| v.as_list())
            .unwrap_or(&[]);

        // Extract ICIs per coda; need ≥ 3 to compute lag-1 over ≥ 2 pairs.
        let all_icis: Vec<Vec<f64>> = codas
            .iter()
            .filter_map(|coda| coda.get_field("icis").and_then(|v| v.as_list()))
            .map(|list| list.iter().filter_map(|v| v.as_f64()).collect::<Vec<f64>>())
            .filter(|xs| xs.len() >= 3)
            .collect();

        let observed: Vec<f64> = all_icis.iter().filter_map(|xs| lag1_corr(xs)).collect();
        let n_codas = observed.len();
        if n_codas == 0 {
            return empty_measurement("No codas with ≥ 3 ICIs found.");
        }
        let mean_obs = observed.iter().sum::<f64>() / n_codas as f64;

        // Within-coda permutation null: shuffle each coda's ICIs independently,
        // recompute the pooled mean lag-1, repeat N times.
        let mut rng = StdRng::seed_from_u64(self.seed);
        let mut null_means: Vec<f64> = Vec::with_capacity(self.n_permutations);
        for _ in 0..self.n_permutations {
            let mut sum = 0.0_f64;
            let mut count = 0_usize;
            for xs in &all_icis {
                let mut shuffled = xs.clone();
                shuffle_in_place(&mut rng, &mut shuffled);
                if let Some(c) = lag1_corr(&shuffled) {
                    sum += c;
                    count += 1;
                }
            }
            if count > 0 {
                null_means.push(sum / count as f64);
            }
        }

        let null_n = null_means.len() as f64;
        if null_n == 0.0 {
            return empty_measurement("Permutation null produced no samples.");
        }
        let null_mean = null_means.iter().sum::<f64>() / null_n;
        let null_var =
            null_means.iter().map(|m| (m - null_mean).powi(2)).sum::<f64>() / null_n;
        let null_std = null_var.sqrt();
        let z_score = if null_std > 0.0 {
            (mean_obs - null_mean) / null_std
        } else {
            0.0
        };
        let abs_dev = (mean_obs - null_mean).abs();
        let n_extreme = null_means
            .iter()
            .filter(|m| (**m - null_mean).abs() >= abs_dev)
            .count();
        let p_value = (n_extreme as f64 + 1.0) / (null_n + 1.0);
        let decisive = z_score.abs() > 3.0 && mean_obs.abs() > 0.2;

        let values = Value::tree([
            ("mean_lag1_corr", Value::float(mean_obs)),
            ("z_score", Value::float(z_score)),
            ("p_value", Value::float(p_value)),
            ("n_codas", Value::float(n_codas as f64)),
            ("n_permutations", Value::float(self.n_permutations as f64)),
            ("null_mean", Value::float(null_mean)),
            ("null_std", Value::float(null_std)),
        ]);
        let notes = format!(
            "Lag-1 Pearson autocorrelation of ICIs pooled across {} codas (≥3 ICIs each); within-coda shuffle null with {} permutations.",
            n_codas, self.n_permutations
        );

        let measurement = Value::tree([
            ("_type", Value::from("Measurement")),
            ("op_id", Value::from("LagAutocorrelation")),
            ("values", values),
            ("decisive", Value::Bool(decisive)),
            ("notes", Value::from(notes.as_str())),
        ]);
        Update::value(Value::tree([("measurement", measurement)]))
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
    fn as_any_mut(&mut self) -> &mut dyn Any {
        self
    }
}

fn empty_measurement(notes: &str) -> Update {
    Update::value(Value::tree([(
        "measurement",
        Value::tree([
            ("_type", Value::from("Measurement")),
            ("op_id", Value::from("LagAutocorrelation")),
            ("values", Value::map()),
            ("decisive", Value::Bool(false)),
            ("notes", Value::from(notes)),
        ]),
    )]))
}

/// Register coda's statistical operationalizations into a [`ProcessRegistry`].
pub fn register_processes(reg: &mut ProcessRegistry) {
    reg.register("LagAutocorrelation", |config| {
        ProcessNode::Step(Box::new(LagAutocorrelation::from_config(&config)))
    });
}
