//! `lockfile.rs` — `project.lock`: the resolved dependency graph as deterministic
//! `.ys`-data (#67, Phase 2 P2d).
//!
//! The lockfile is the **colimit's chosen section** (`docs/packages-ecosystem.md`):
//! the resolver picks ONE version per package name so the dependency colimit is
//! well-defined, and the lockfile pins exactly that choice — one entry per name, the
//! graph edges, the source — so a build is reproducible. It is `.ys`-as-data (a `def
//! lock = { packages: … }` record), written through the same parser/unparser the
//! manifest + `coord set` use, and **gated** (the rendered text must re-parse), so it
//! can never be written malformed.
//!
//! ```text
//! # project.lock — GENERATED
//! def lock = {
//!   packages: {
//!     a: { version: '1.0.0', source: '../a', dependencies: ['d'] },
//!     d: { version: '1.0.0', source: '../d', dependencies: [] },
//!   },
//! }
//! ```

use std::path::{Path, PathBuf};

use indexmap::IndexMap;

use crate::ast::{Def, Expr, Program, StringLit};
use crate::manifest::{string_field, string_list};
use crate::resolver::ResolvedPackage;
use crate::version::Version;

/// The lockfile name, written next to the root `project.ys`.
pub const LOCKFILE: &str = "project.lock";

const HEADER: &str = "\
# project.lock — GENERATED by `chrysalis` (#67). The resolved dependency graph: one
# version per package name (the colimit's chosen section), pinned for reproducible
# builds. Do NOT edit by hand — regenerated on resolve.
";

/// A pinned package in the lockfile.
#[derive(Debug, Clone, PartialEq)]
pub struct LockedPackage {
    pub name: String,
    pub version: Version,
    /// The package's source, relative to the lockfile's directory.
    pub source: String,
    /// The names of this package's direct dependencies.
    pub dependencies: Vec<String>,
}

/// Render the resolved `graph` (already sorted by name) as `project.lock` TEXT.
/// `root_dir` is where the lockfile lives — package sources are recorded relative to
/// it (portable + machine-independent). Deterministic + gated (the text re-parses).
pub fn render(graph: &[ResolvedPackage], root_dir: &Path) -> Result<String, String> {
    let mut packages: IndexMap<String, Expr> = IndexMap::new();
    for pkg in graph {
        let mut rec: IndexMap<String, Expr> = IndexMap::new();
        rec.insert("version".to_string(), str_expr(&pkg.version.to_string()));
        rec.insert(
            "source".to_string(),
            str_expr(&relativize(&pkg.source, root_dir).to_string_lossy()),
        );
        rec.insert(
            "dependencies".to_string(),
            Expr::List(pkg.dependencies.iter().map(|d| str_expr(d)).collect()),
        );
        packages.insert(pkg.name.clone(), Expr::Record(rec));
    }
    let mut lock: IndexMap<String, Expr> = IndexMap::new();
    lock.insert("packages".to_string(), Expr::Record(packages));

    let mut program = Program::new();
    program.push(Def::Binding {
        name: "lock".to_string(),
        schema: None,
        value: Expr::Record(lock),
    });
    let text = format!("{HEADER}{}", crate::unparse::unparse(&program));

    // GATE — a lockfile only ever goes good → good.
    crate::parse::parse_program(&text)
        .map_err(|e| format!("lockfile would not re-parse (nothing written): {e}"))?;
    Ok(text)
}

/// Write `project.lock` next to the root manifest, only if its content changed (no
/// needless mtime churn).
pub fn write(graph: &[ResolvedPackage], root_dir: &Path) -> Result<(), String> {
    let text = render(graph, root_dir)?;
    let path = root_dir.join(LOCKFILE);
    if std::fs::read_to_string(&path).map(|c| c == text).unwrap_or(false) {
        return Ok(());
    }
    std::fs::write(&path, &text).map_err(|e| format!("write {}: {e}", path.display()))
}

/// Parse `project.lock` source back into the pinned packages (sorted by name —
/// `parse` preserves the file's order, which `render` writes sorted).
pub fn parse(src: &str) -> Result<Vec<LockedPackage>, String> {
    let program =
        crate::parse::parse_program(src).map_err(|e| format!("parse {LOCKFILE}: {e}"))?;
    let fields = program
        .defs
        .iter()
        .find_map(|d| match d {
            Def::Binding {
                name,
                value: Expr::Record(fields),
                ..
            } if name == "lock" => Some(fields),
            _ => None,
        })
        .ok_or_else(|| format!("{LOCKFILE} has no `def lock = {{ … }}` record"))?;

    let packages = match fields.get("packages") {
        Some(Expr::Record(p)) => p,
        _ => return Err(format!("{LOCKFILE}: `lock` needs a `packages` record")),
    };

    let mut out = Vec::new();
    for (name, spec) in packages {
        let spec = match spec {
            Expr::Record(s) => s,
            _ => return Err(format!("{LOCKFILE}: package `{name}` must be a record")),
        };
        let version = string_field(spec, "version")
            .ok_or_else(|| format!("{LOCKFILE}: package `{name}` needs a `version`"))?
            .parse::<Version>()
            .map_err(|e| format!("{LOCKFILE}: package `{name}`: {e}"))?;
        let source = string_field(spec, "source")
            .ok_or_else(|| format!("{LOCKFILE}: package `{name}` needs a `source`"))?;
        let dependencies = match spec.get("dependencies") {
            Some(e) => string_list(e)
                .ok_or_else(|| format!("{LOCKFILE}: package `{name}` dependencies must be strings"))?,
            None => Vec::new(),
        };
        out.push(LockedPackage {
            name: name.clone(),
            version,
            source,
            dependencies,
        });
    }
    Ok(out)
}

/// Read + parse `<dir>/project.lock`, or `None` if it doesn't exist.
pub fn load(dir: &Path) -> Result<Option<Vec<LockedPackage>>, String> {
    let path = dir.join(LOCKFILE);
    match std::fs::read_to_string(&path) {
        Ok(src) => parse(&src).map(Some),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(format!("read {}: {e}", path.display())),
    }
}

fn str_expr(s: &str) -> Expr {
    Expr::Str(StringLit::plain(s))
}

/// `target` expressed relative to `base` (both canonicalized first, so a `..`-laden
/// resolved path becomes a clean relative one). Falls back to the raw target if
/// canonicalization fails (a path that no longer exists).
fn relativize(target: &Path, base: &Path) -> PathBuf {
    let target = target.canonicalize().unwrap_or_else(|_| target.to_path_buf());
    let base = base.canonicalize().unwrap_or_else(|_| base.to_path_buf());
    let t: Vec<_> = target.components().collect();
    let b: Vec<_> = base.components().collect();
    let common = t.iter().zip(b.iter()).take_while(|(x, y)| x == y).count();
    let mut rel = PathBuf::new();
    for _ in 0..(b.len() - common) {
        rel.push("..");
    }
    for c in &t[common..] {
        rel.push(c.as_os_str());
    }
    if rel.as_os_str().is_empty() {
        rel.push(".");
    }
    rel
}

#[cfg(test)]
mod tests {
    use super::*;

    fn pkg(name: &str, version: &str, source: &str, deps: &[&str]) -> ResolvedPackage {
        ResolvedPackage {
            name: name.to_string(),
            version: version.parse().unwrap(),
            source: PathBuf::from(source),
            dependencies: deps.iter().map(|s| s.to_string()).collect(),
        }
    }

    /// A unique temp root with `a/` and `d/` subdirs created, so `relativize`
    /// (which canonicalizes) yields clean relative sources.
    fn temp_root_with_dirs(tag: &str) -> PathBuf {
        let root = std::env::temp_dir().join(format!("lock-test-{tag}-{}", std::process::id()));
        std::fs::create_dir_all(root.join("a")).unwrap();
        std::fs::create_dir_all(root.join("d")).unwrap();
        root
    }

    #[test]
    fn renders_and_reparses_the_graph() {
        let root = temp_root_with_dirs("roundtrip");
        let graph = vec![
            pkg("a", "1.0.0", &root.join("a").to_string_lossy(), &["d"]),
            pkg("d", "1.2.3", &root.join("d").to_string_lossy(), &[]),
        ];
        let text = render(&graph, &root).expect("renders + gates");
        assert!(text.contains("def lock"));

        let parsed = parse(&text).expect("re-parses");
        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed[0].name, "a");
        assert_eq!(parsed[0].version, Version::new(1, 0, 0));
        assert_eq!(parsed[0].dependencies, vec!["d".to_string()]);
        assert_eq!(parsed[0].source, "a"); // relative to root
        assert_eq!(parsed[1].name, "d");
        assert_eq!(parsed[1].version, Version::new(1, 2, 3));

        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn render_is_deterministic() {
        let root = temp_root_with_dirs("deterministic");
        let graph = vec![
            pkg("d", "1.0.0", &root.join("d").to_string_lossy(), &[]),
            pkg("a", "1.0.0", &root.join("a").to_string_lossy(), &["d"]),
        ];
        let once = render(&graph, &root).unwrap();
        let twice = render(&graph, &root).unwrap();
        assert_eq!(once, twice, "the lockfile is reproducible");

        std::fs::remove_dir_all(&root).ok();
    }
}
